### ISSUE TITLE
QGuiApplicationPrivate::platformTheme()->createPlatformDialogHelper(QPlatformTheme::FileDialog) return NULL

### ISSUE THREAD

**Issue by xiangzhai** [kullo/qml-file-dialog-demo#2]
My environment:

```
qmake -v
QMake version 3.0
Using Qt version 5.2.0 in /usr/lib
```

```
uname -a
Linux 3.12.7-30 #1 SMP PREEMPT Wed Aug 27 13:08:44 CST 2014 x86_64 GNU/Linux
```

KDE 4.12.1

I have no idea why QGuiApplicationPrivate::platformTheme()->createPlatformDialogHelper(QPlatformTheme::FileDialog) return NULL!

I have a look at qtbase/src/widgets/dialogs/qdialog.cpp use createPlatformDialogHelper too https://github.com/qtproject/qtbase/blob/dev/src/widgets/dialogs/qdialog.cpp#L83

Please someone give me some advise, thanks a lot!

Regards,
Leslie Zhai

**Comment by xiangzhai** [comment]
I fixed ;) http://qt-project.org/forums/viewthread/35441 just use QApplication.

**Comment by webmaster128** [comment]
Ah, good point. Yes you need Qt widgets support. Maybe I can add a check for that.

**Comment by webmaster128** [comment]
Thanks a lot. I added a runtime check which ensures that widget support is available: https://github.com/kullo/qml-file-dialog-demo/commit/2470d84b865450df1821174bd9d30e6acd1b6baa I think that saves a lot of debugging efford for others, especially because having no widgets support will be a common case in QML applications. If you have an idea how it can be checked at compile time, let me know.
